version: "2"

networks:
  goldenram:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
          gateway: 10.1.0.1

services:
  head:
    privileged: true
    build:
      context: ./head
    cap_add:
      - ALL
    networks:
      goldenram:
        ipv4_address: 10.1.0.2
    extra_hosts:
      - "head.golden.ram:10.1.0.2"
      - "ldap.golden.ram:10.1.0.3"
      - "compute-1.golden.ram:10.1.0.5"
      - "compute-2.golden.ram:10.1.0.6"

  ldap:
    privileged: true
    build:
      context: ./ldap
    cap_add:
      - ALL
    networks:
      goldenram:
        ipv4_address: 10.1.0.3
    extra_hosts:
      - "head.golden.ram:10.1.0.2"
      - "ldap.golden.ram:10.1.0.3"
      - "compute-1.golden.ram:10.1.0.5"
      - "compute-2.golden.ram:10.1.0.6"

#  compute-1:
#    build:
#      context: ./compute
#    networks:
#      goldenram:
#        ipv4_address: 10.1.0.5
#    extra_hosts:
#      - "head.golden.ram:10.1.0.2"
#      - "ldap.golden.ram:10.1.0.3"
#      - "compute-1.golden.ram:10.1.0.5"
#      - "compute-2.golden.ram:10.1.0.6"
#  compute-2:
#    build:
#      context: ./compute
#    networks:
#      goldenram:
#        ipv4_address: 10.1.0.6
#    extra_hosts:
#      - "head.golden.ram:10.1.0.2"
#      - "ldap.golden.ram:10.1.0.3"
#      - "compute-1.golden.ram:10.1.0.5"
#      - "compute-2.golden.ram:10.1.0.6"
